=head1 NAME

memc_set

=head1 UDF 

Libmemcached User Defined Function for MySQL 

=head1 SYNOPSIS

memc_stats('hostname1,hostname2');

memc_stat_get_keys();

=head1 DESCRIPTION

memc_stats() is a UDF used to retrieve the statistics of memcached server (one or more) state 

memc_stat_get_keys() is a UDF used to retrieve the various memcached state keys 

memc_stat_get_value() is a UDF used to retrieve a specific memcached state key from a specific server 

=head1 RETURN

NULL

=head1 HOME

To find out more information please check:
L<http://hg.tangent.org/memcached_functions_mysql>
L<http://tangent.org/552/libmemcached.html>

=head1 INSTALL

CREATE FUNCTION memc_stats RETURNS STRING SONAME "libmemcached_functions_mysql.so";
CREATE FUNCTION memc_stat_get_keys RETURNS STRING SONAME "libmemcached_functions_mysql.so";
CREATE FUNCTION memc_stat_get_value RETURNS STRING SONAME "libmemcached_functions_mysql.so";

=head1 AUTHOR

Patrick Galbraith, E<lt>patg@patg.netE<gt>
Brian Aker, E<lt>brian@tangent.orgE<gt>

=head1 SEE ALSO

memc_set(), memc_delete()...

=cut

